version: '3.8'

services:
  web:
    image: nginx:stable-alpine
    container_name: natflux_nginx
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:80"
